import type { Installer } from './types'

// Used as fallback when Supabase isn't connected yet
export const MOCK_INSTALLERS: Installer[] = [
  {
    id: '1',
    name: 'Meridian Solar Engineering',
    city: 'Johannesburg',
    province: 'Gauteng',
    blurb: 'Johannesburg\'s most trusted C&I solar contractor. Over a decade delivering high-performance rooftop and ground-mount systems to manufacturers, logistics hubs, and retail parks across Gauteng.',
    services: ['Commercial Rooftop', 'Ground-Mount C&I', 'Battery Storage', 'O&M Contracts'],
    verified: true,
    years_in_business: 12,
    min_system_size_kw: 50,
    max_system_size_kw: 5000,
    phone: '+27 11 234 5678',
    email: 'info@meridiansolar.co.za',
    website: 'https://meridiansolar.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'SunPower Africa',
    city: 'Cape Town',
    province: 'Western Cape',
    blurb: 'Cape Town\'s premier solar installer for commercial and industrial clients. Specialists in large-format PV, energy storage, and grid-tied systems for the hospitality, retail, and agri sectors.',
    services: ['Commercial PV', 'Industrial Systems', 'Energy Storage', 'Solar Finance Advisory'],
    verified: true,
    years_in_business: 9,
    min_system_size_kw: 30,
    max_system_size_kw: 10000,
    phone: '+27 21 456 7890',
    email: 'projects@sunpowerafrica.co.za',
    website: 'https://sunpowerafrica.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    name: 'Beacon Energy Solutions',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    blurb: 'KwaZulu-Natal\'s leading commercial solar contractor. We design and build cost-effective solar systems for warehouses, shopping centres, and cold storage facilities across the province.',
    services: ['Commercial Solar', 'Cold Storage Optimisation', 'Wheeling Agreements', 'Power Purchase Agreements'],
    verified: true,
    years_in_business: 7,
    min_system_size_kw: 100,
    max_system_size_kw: 8000,
    phone: '+27 31 567 8901',
    email: 'hello@beaconenergy.co.za',
    website: 'https://beaconenergy.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'AfriSun Energy',
    city: 'Sandton',
    province: 'Gauteng',
    blurb: 'Sandton-based C&I solar developer with a 400+ MW portfolio. We handle projects from feasibility through to grid connection and long-term operations across Southern Africa.',
    services: ['C&I Development', 'Grid Connection', 'Power Purchase Agreements', 'Operations & Maintenance'],
    verified: true,
    years_in_business: 11,
    min_system_size_kw: 500,
    max_system_size_kw: 50000,
    phone: '+27 10 789 0123',
    email: 'projects@afrisun.co.za',
    website: 'https://afrisun.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Sol-Tech Engineers',
    city: 'Cape Town',
    province: 'Western Cape',
    blurb: 'Engineering-first solar company founded by electrical engineers. We specialise in technically complex C&I projects: high-voltage systems, transformer-coupled arrays, and custom BMS integration.',
    services: ['HV Solar Engineering', 'BMS Integration', 'Transformer Systems', 'Technical Due Diligence'],
    verified: true,
    years_in_business: 11,
    min_system_size_kw: 200,
    max_system_size_kw: 20000,
    phone: '+27 21 890 1234',
    email: 'eng@soltechsa.co.za',
    website: 'https://soltechsa.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    name: 'Cape Verde Solar',
    city: 'George',
    province: 'Western Cape',
    blurb: 'Garden Route specialists servicing the agri, hospitality, and light industrial sectors. We design systems for load-shedding resilience and long-term energy cost reduction.',
    services: ['Agricultural Solar', 'Hospitality Systems', 'Diesel Offset', 'Remote Monitoring'],
    verified: true,
    years_in_business: 8,
    min_system_size_kw: 20,
    max_system_size_kw: 2000,
    phone: '+27 44 345 6789',
    email: 'info@capeVerdesolar.co.za',
    website: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    name: 'Coastal Solar KZN',
    city: 'Durban',
    province: 'KwaZulu-Natal',
    blurb: 'Durban-based installer with a reputation for clean, professional C&I installations. We work with property owners and facilities managers to maximise solar returns with minimal disruption.',
    services: ['Rooftop Commercial', 'Carport Solar', 'Battery Backup', 'Meter & Grid Compliance'],
    verified: true,
    years_in_business: 6,
    min_system_size_kw: 50,
    max_system_size_kw: 4000,
    phone: '+27 31 678 9012',
    email: 'info@coastalsolarkzn.co.za',
    website: 'https://coastalsolarkzn.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Bright Future Solar',
    city: 'Pretoria',
    province: 'Gauteng',
    blurb: 'Pretoria-based commercial installer serving government buildings, schools, and SME factories. Competitive pricing, fast delivery, and a strong track record on public-sector projects.',
    services: ['Government Solar', 'School & Campus Systems', 'SME Installations', 'Net Metering'],
    verified: false,
    years_in_business: 5,
    min_system_size_kw: 10,
    max_system_size_kw: 1500,
    phone: '+27 12 456 7890',
    email: 'sales@brightfuture.co.za',
    website: 'https://brightfuturesolar.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '9',
    name: 'Highveld Energy',
    city: 'Johannesburg',
    province: 'Gauteng',
    blurb: 'Young and hungry Joburg installer building a portfolio in the mid-market commercial space. Focused on transparent quoting, fast turnaround, and quality workmanship on every job.',
    services: ['Commercial PV', 'Battery Backup', 'System Upgrades', 'Energy Audits'],
    verified: false,
    years_in_business: 3,
    min_system_size_kw: 20,
    max_system_size_kw: 1000,
    phone: '+27 11 890 1234',
    email: 'info@highveldenergy.co.za',
    website: null,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '10',
    name: 'SolarTech SA',
    city: 'Bellville',
    province: 'Western Cape',
    blurb: 'Bellville-based solar contractor serving the Cape Metro with no-fuss, well-priced commercial installations. Strong partnerships with Tier-1 panel manufacturers and local electrical contractors.',
    services: ['Rooftop Commercial', 'Inverter & Storage', 'Compliance Certificates', 'Annual Maintenance'],
    verified: false,
    years_in_business: 4,
    min_system_size_kw: 15,
    max_system_size_kw: 800,
    phone: '+27 21 234 5678',
    email: 'info@solartechsa.co.za',
    website: 'https://solartechsa.co.za',
    created_at: '2024-01-01T00:00:00Z',
  },
]
